/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.csic.iiia.normlab.launcher.ui;

import java.awt.Frame;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Javier Morales (jmorales@iiia.csic.es)
 */
public class DialogExperimentsConsole extends javax.swing.JDialog {

	private static final long serialVersionUID = -1162681743865859603L;

	public static Thread threadExperiments;
	private boolean runningExperiments;

	/**
	 * Creates new form DialogExperimentsConsole
	 */
	public DialogExperimentsConsole(Frame parent, boolean modal, 
			Thread threadExps) {

		super(parent, modal);
		
		initComponents();
		setResizable(false);
		
		threadExperiments = threadExps;
		runningExperiments = true;
		
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
	}

	/**
	 * 
	 * @param evt
	 */
	private void btnStopActionPerformed(ActionEvent evt) {
		int dialogButton = JOptionPane.YES_NO_OPTION;
		int dialogResult = JOptionPane.showConfirmDialog(this, 
				"Do you really want to stop all experiments?", "Stop experiments?", 
				dialogButton);

		if(dialogResult == 0) {
			runningExperiments = false;
			threadExperiments.interrupt();
		} 
	}

	/**
	 * 
	 * @param evt
	 */
	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {      
		int dialogResult = 0;

		if(runningExperiments) {
			int dialogButton = JOptionPane.YES_NO_OPTION;
			dialogResult = JOptionPane.showConfirmDialog(this, 
					"Are you sure you want to close this window?\n"
					+ "It will stop running experiments", "Close this window?", 
					dialogButton);
		}
		if(dialogResult == 0) {
			disposeConsole();
		}
	}     
  
	/**
	 * 
	 */
	private void disposeConsole() {
		threadExperiments.interrupt();
		this.dispose();
	}

	/**
	 * 
	 * @return
	 */
	public JTextArea getConsole() {
		return this.txtConsole;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		panelConsole = new javax.swing.JPanel();
		lblTitle = new javax.swing.JLabel();
		scrPanelConsole = new javax.swing.JScrollPane();
		txtConsole = new javax.swing.JTextArea();
		btnStop = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(panelConsole);
		panelConsole.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblTitle.setBackground(new java.awt.Color(255, 255, 255));
		lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		lblTitle.setIcon(new javax.swing.ImageIcon("misc/launcher/icons/console.png")); // NOI18N
		lblTitle.setText(" NormLab experiments console");
		lblTitle.setToolTipText("");
		lblTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		lblTitle.setOpaque(true);

		txtConsole.setColumns(20);
		txtConsole.setRows(5);
		scrPanelConsole.setViewportView(txtConsole);

		btnStop.setIcon(new javax.swing.ImageIcon("misc/launcher/icons/stop.png")); // NOI18N
		btnStop.setText("Stop experiments");
		btnStop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnStopActionPerformed(evt);
			}
		});
		
		btnExit.setIcon(new javax.swing.ImageIcon("misc/launcher/icons/exit_small.png")); // NOI18N
		btnExit.setText("Exit");
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});
		
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrPanelConsole, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnStop)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblTitle)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnStop)
                .addComponent(btnExit))
            .addGap(10, 10, 10)
            .addComponent(scrPanelConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addContainerGap())
    );

		pack();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogExperimentsConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogExperimentsConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogExperimentsConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogExperimentsConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DialogExperimentsConsole dialog = new DialogExperimentsConsole(new javax.swing.JFrame(), 
						true, threadExperiments);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnStop;
	private javax.swing.JButton btnExit;
	private javax.swing.JPanel panelConsole;
	private javax.swing.JScrollPane scrPanelConsole;
	private javax.swing.JTextArea txtConsole;
	private javax.swing.JLabel lblTitle;
	// End of variables declaration//GEN-END:variables
}
